name: Cypress tests
on:
  push:
    branches: [main, master, lastHW]
  pull_request:
    branches: [main, master, lastHW]
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/inventoryTests.cy.js
