name: Cypress tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  cypress-run:
    name: Cypress run
    run-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/inventoryTests.cy.js
